services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${URL}
      - VALIDATION=${VALIDATION}
      - SUBDOMAINS=${SUBDOMAINS}
      - CERTPROVIDER=${CERTPROVIDER}
      - DNSPLUGIN=${DNSPLUGIN}
      - EMAIL=${EMAIL}
      - ONLY_SUBDOMAINS=${ONLY_SUBDOMAINS}
      - STAGING=${STAGING}
    volumes:
      - ./config:/config
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
