version: "3.8"

services:
  kamailio:
    image: kamailio/kamailio-ci:latest
    container_name: kamailio
    restart: unless-stopped
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5061:5061/tcp"
    volumes:
      - ./config:/etc/kamailio
    environment:
      - SHM_MEMORY=64
      - PKG_MEMORY=8
    cap_add:
      - NET_ADMIN
