services:
  bencher-api:
    image: ghcr.io/bencherdev/bencher-api:latest
    container_name: bencher_api
    ports:
      - 61016:61016
    volumes:
      - api-config:/etc/bencher
      - api-data:/var/lib/bencher/data
    # environment:
    #   - BENCHER_CONFIG=
    #   - BENCHER_CONFIG_PATH=

  bencher-console:
    image: ghcr.io/bencherdev/bencher-console:latest
    container_name: bencher_console
    ports:
      - 3000:3000
    environment:
      - BENCHER_API_URL=http://127.0.0.1:61016
      - INTERNAL_API_URL=http://bencher-api:61016
    depends_on:
      - bencher-api

volumes:
  api-config:
  api-data:
