upstream forkapi {
    server unix:///tmp/uwsgi/forkapi.sock;
}

upstream forkrecipes {
    server unix:///tmp/uwsgi/forkrecipes.sock;
}

server {
    listen 80;
    server_name localhost;

    location /api/ {
        uwsgi_pass forkapi;
        include uwsgi_params;
    }

    location /static/api/ {
        alias /forkapi/static/;
    }

    location /media/ {
        alias /forkapi/media/;
    }

    location /static/ {
        alias /fork_recipes/static/;
    }

    location / {
        uwsgi_pass forkrecipes;
        include uwsgi_params;
    }
}
