services:
  maloja:
    image: krateng/maloja:${MALOJA_VERSION:-latest}
    container_name: maloja
    restart: unless-stopped
    ports:
      - "${MALOJA_PORT:-42010}:42010"
    environment:
      MALOJA_SKIP_SETUP: "true"
      MALOJA_DATA_DIRECTORY: /data
    volumes:
      - ./data:/data
