services:
  origin:
    image: airensoft/ovenmediaengine:latest
    container_name: ome-origin
    restart: always
    ports:
      - "${OME_RTMP_PORT:-1935}:1935/tcp"
      - "${OME_SRT_PORT:-9999}:9999/udp"
      - "${OME_LLHLS_PORT:-3333}:3333/tcp"
      - "${OME_WEBRTC_TLS_PORT:-3334}:3334/tcp"
      - "${OME_TURN_PORT:-3478}:3478/tcp"
      - "10000-10004:10000-10004/udp"
    environment:
      - OME_HOST_IP=${OME_HOST_IP}
      - OME_ORIGIN_PORT=9000
      - OME_RTMP_PROV_PORT=1935
      - OME_SRT_PROV_PORT=9999
      - OME_LLHLS_STREAM_PORT=3333
      - OME_WEBRTC_SIGNALLING_PORT=3333
      - OME_WEBRTC_SIGNALLING_TLS_PORT=3334
      - OME_WEBRTC_TCP_RELAY_PORT=3478
      - OME_WEBRTC_CANDIDATE_PORT=10000-10004/udp
    command: /opt/ovenmediaengine/bin/ome_launcher.sh -c origin_conf
