services:
  webarchive:
    image: ghcr.io/derfenix/webarchive:latest
    ports:
      - "5001:5001"
    environment:
      - LOGGING_DEBUG=true
      - API_ADDRESS=0.0.0.0:5001
      - PDF_DPI=300
      - DB_PATH=/db
    volumes:
      - ./db:/db
    restart: unless-stopped
