volumes:
  pg_data:

networks:
  router_net:

services:
  pg:
    image: docker.io/postgres:latest
    ports:
      - "${PG_PORT:-5432}:5432"
    networks:
      - router_net
    volumes:
      - pg_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-db_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-db_pass}
      - POSTGRES_DB=${POSTGRES_DB:-hyperswitch_db}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      retries: 3
      start_period: 5s
      timeout: 5s

  redis-standalone:
    image: docker.io/redis:7
    networks:
      - router_net
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep '^PONG$'"]
      interval: 5s
      retries: 3
      start_period: 5s
      timeout: 5s

  hyperswitch-server:
    image: docker.juspay.io/juspaydotin/hyperswitch-router:standalone
    pull_policy: always
    command: /local/bin/router -f /local/config/docker_compose.toml
    ports:
      - "${HYPERSWITCH_PORT:-8080}:8080"
    networks:
      - router_net
    volumes:
      - ./config:/local/config
      - ./files:/local/bin/files
    depends_on:
      pg:
        condition: service_healthy
      redis-standalone:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 5s
      retries: 3
      start_period: 5s
      timeout: 5s

  hyperswitch-producer:
    image: docker.juspay.io/juspaydotin/hyperswitch-producer:standalone
    pull_policy: always
    command: /local/bin/scheduler -f /local/config/docker_compose.toml
    networks:
      - router_net
    volumes:
      - ./config:/local/config
    depends_on:
      hyperswitch-server:
        condition: service_healthy

  hyperswitch-consumer:
    image: docker.juspay.io/juspaydotin/hyperswitch-consumer:standalone
    pull_policy: always
    command: /local/bin/scheduler -f /local/config/docker_compose.toml
    networks:
      - router_net
    volumes:
      - ./config:/local/config
    depends_on:
      hyperswitch-server:
        condition: service_healthy

  hyperswitch-control-center:
    image: docker.juspay.io/juspaydotin/hyperswitch-control-center:latest
    pull_policy: always
    ports:
      - "${CONTROL_CENTER_PORT:-9000}:9000"
    networks:
      - router_net
    environment:
      - apiBaseUrl=http://localhost:${HYPERSWITCH_PORT:-8080}
      - sdkBaseUrl=http://localhost:${SDK_PORT:-9050}/HyperLoader.js
