services:
  front:
    state: exited
    exit_code: 0
  auth:
  api:
    state: exited
    exit_code: 1
  scanner:
    state: exited
    exit_code: 0
  transcoder:
    health: starting
  postgres:
    state: paused
