services:
  accent:
    image: mirego/accent
    ports:
      - "4000:4000"
    depends_on:
      - postgresql
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://postgres:accent@postgresql:5432/accent
      - DUMMY_LOGIN_ENABLED=true
    restart: unless-stopped

  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_DB=accent
      - POSTGRES_PASSWORD=accent
    volumes:
      - accent_psql:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  accent_psql:
