services:
  database:
    image: mysql:8.4
    container_name: traccar-db
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - traccar_db:/var/lib/mysql

  traccar:
    image: traccar/traccar:latest
    container_name: traccar
    restart: unless-stopped
    depends_on:
      - database
    environment:
      CONFIG_USE_ENVIRONMENT_VARIABLES: "true"
      DATABASE_DRIVER: com.mysql.cj.jdbc.Driver
      DATABASE_URL: >-
        jdbc:mysql://database:3306/${MYSQL_DATABASE}
        ?zeroDateTimeBehavior=round
        &serverTimezone=UTC
        &allowPublicKeyRetrieval=true
        &useSSL=false
        &allowMultiQueries=true
        &autoReconnect=true
        &useUnicode=yes
        &characterEncoding=UTF-8
        &sessionVariables=sql_mode=''
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8082/api/health"]
      interval: 2m
      timeout: 5s
      start_period: 1h
      retries: 3
    ports:
      - "${TRACCAR_WEB_PORT}:8082"
      - "${TRACCAR_DEVICE_PORTS}:5000-5500"
    volumes:
      - traccar_logs:/opt/traccar/logs

volumes:
  traccar_db:
  traccar_logs:
