services:
  webapp:
    image: papermerge/papermerge:3.5
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - "12000:80"
    environment:
      PAPERMERGE__SECURITY__SECRET_KEY: "${SECRET_KEY}"
      PAPERMERGE__AUTH__USERNAME: "${AUTH_USERNAME}"
      PAPERMERGE__AUTH__PASSWORD: "${AUTH_PASSWORD}"
      PAPERMERGE__DATABASE__TYPE: postgres
      PAPERMERGE__DATABASE__USER: "${DB_USER}"
      PAPERMERGE__DATABASE__NAME: "${DB_NAME}"
      PAPERMERGE__DATABASE__PASSWORD: "${DB_PASSWORD}"
      PAPERMERGE__DATABASE__HOST: db
      PAPERMERGE__DATABASE__PORT: "5432"
      PAPERMERGE__REDIS__URL: "redis://redis:6379/0"
    volumes:
      - media_data:/core_app/media

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped

volumes:
  pgdata:
  media_data:
