services:
  svix-server:
    image: svix/svix-server:latest
    restart: unless-stopped
    ports:
      - "${SVIX_PORT:-8071}:8071"
    environment:
      WAIT_FOR: "true"
      SVIX_REDIS_DSN: "redis://redis:6379"
      SVIX_DB_DSN: "postgresql://${PG_USER}:${PG_PASSWORD}@pgbouncer/${PG_DATABASE}"
      SVIX_JWT_SECRET: ${SVIX_JWT_SECRET}
    healthcheck:
      test: ["CMD-SHELL", "svix-server healthcheck http://localhost:8071"]
      interval: 5s
      timeout: 5s
      retries: 30
    depends_on:
      pgbouncer:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgbouncer:
    image: edoburu/pgbouncer:1.22.0
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_USER: ${PG_USER}
      DB_PASSWORD: ${PG_PASSWORD}
      MAX_CLIENT_CONN: "500"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: "--save 60 500 --appendonly yes --appendfsync everysec"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
