services:
  php-fpm:
    state: exited
    exit_code: 0
    health: starting
  sogo:
  postfix:
    needs_recreation: true
  nginx:
    needs_recreation: true
  acme:
  dockerapi:
    health: unhealthy
