CREATE SCHEMA IF NOT EXISTS listaway;
GRANT CREATE, USAGE ON SCHEMA listaway TO listaway;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA listaway TO listaway;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA listaway TO listaway;
