services:
  jupyterlab:
    image: quay.io/jupyter/scipy-notebook:latest
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: unless-stopped

volumes:
  notebooks:
