services:
  kiwix-serve:
    image: ghcr.io/kiwix/kiwix-serve:3.8.2
    container_name: kiwix-serve
    command: /data/*.zim
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    restart: unless-stopped
