services:
  bytestash:
    image: ghcr.io/jordan-dalby/bytestash:latest
    container_name: bytestash
    restart: always
    ports:
      - "${BYTESTASH_PORT:-5000}:5000"
    volumes:
      - ./data/snippets:/data/snippets
    environment:
      - BASE_PATH=${BASE_PATH:-}
      - JWT_SECRET=${JWT_SECRET:-changeme-jwt-secret}
      - TOKEN_EXPIRY=${TOKEN_EXPIRY:-24h}
      - ALLOW_NEW_ACCOUNTS=${ALLOW_NEW_ACCOUNTS:-true}
      - DEBUG=${DEBUG:-false}
      - DISABLE_ACCOUNTS=${DISABLE_ACCOUNTS:-false}
      - DISABLE_INTERNAL_ACCOUNTS=${DISABLE_INTERNAL_ACCOUNTS:-false}
      - OIDC_ENABLED=${OIDC_ENABLED:-false}
