services:
  handbrake-server:
    image: ghcr.io/thenickoftime/handbrake-web-server:latest
    container_name: handbrake-web-server
    user: "1000:1000"
    ports:
      - "9999:9999"
    volumes:
      - ./data:/data
      - ./video:/video
    restart: unless-stopped

  handbrake-worker:
    image: ghcr.io/thenickoftime/handbrake-web-worker:latest
    container_name: handbrake-web-worker
    user: "1000:1000"
    environment:
      - WORKER_ID=handbrake-worker
      - SERVER_URL=handbrake-server
      - SERVER_PORT=9999
    volumes:
      - ./video:/video
    depends_on:
      - handbrake-server
    restart: unless-stopped
