# Quizmaster Application Configuration
# https://github.com/nymanjens/quizmaster

play.http.secret.key = "change-me-in-production-use-long-random-string"

play.i18n.langs = ["en"]

play.server.http.port = 9000
