services:
  postgres:
    state: paused
  redis:
    state: exited
    exit_code: 0
  celeryworker:
    state: exited
    exit_code: 0
  traefik:
    health: starting
  pihole:
    state: exited
    exit_code: 1
