services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:${AUDIOBOOKSHELF_VERSION:-latest}
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - "${AUDIOBOOKSHELF_PORT:-13378}:80"
    volumes:
      - ./audiobooks:/audiobooks
      - ./podcasts:/podcasts
      - ./metadata:/metadata
      - ./config:/config
