services:
  zot:
    image: ghcr.io/project-zot/zot-minimal-linux-amd64:latest
    container_name: zot
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./config.json:/etc/zot/config.json:ro
      - registry_data:/var/lib/registry

volumes:
  registry_data:
