/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/settings/About.vue')['default']
    AgentStackList: typeof import('./src/components/AgentStackList.vue')['default']
    Appearance: typeof import('./src/components/settings/Appearance.vue')['default']
    ArrayInput: typeof import('./src/components/ArrayInput.vue')['default']
    ArraySelect: typeof import('./src/components/ArraySelect.vue')['default']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next')['BDropdownDivider']
    BDropdownForm: typeof import('bootstrap-vue-next')['BDropdownForm']
    BDropdownGroup: typeof import('bootstrap-vue-next')['BDropdownGroup']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BDropdownItemButton: typeof import('bootstrap-vue-next')['BDropdownItemButton']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    CollapsibleSection: typeof import('./src/components/CollapsibleSection.vue')['default']
    Confirm: typeof import('./src/components/Confirm.vue')['default']
    ConsoleCheatsheet: typeof import('./src/components/ConsoleCheatsheet.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    ContainerList: typeof import('./src/components/ContainerList.vue')['default']
    ContainerListItem: typeof import('./src/components/ContainerListItem.vue')['default']
    DockerStat: typeof import('./src/components/DockerStat.vue')['default']
    General: typeof import('./src/components/settings/General.vue')['default']
    GlobalEnv: typeof import('./src/components/settings/GlobalEnv.vue')['default']
    HiddenInput: typeof import('./src/components/HiddenInput.vue')['default']
    ImageList: typeof import('./src/components/ImageList.vue')['default']
    ImageListItem: typeof import('./src/components/ImageListItem.vue')['default']
    ListHeader: typeof import('./src/components/ListHeader.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NetworkInput: typeof import('./src/components/NetworkInput.vue')['default']
    NetworkList: typeof import('./src/components/NetworkList.vue')['default']
    NetworkListItem: typeof import('./src/components/NetworkListItem.vue')['default']
    ProgressTerminal: typeof import('./src/components/ProgressTerminal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Security: typeof import('./src/components/settings/Security.vue')['default']
    ServiceActionBar: typeof import('./src/components/ServiceActionBar.vue')['default']
    StackList: typeof import('./src/components/StackList.vue')['default']
    StackListItem: typeof import('./src/components/StackListItem.vue')['default']
    Terminal: typeof import('./src/components/Terminal.vue')['default']
    ToastBody: typeof import('./src/components/ToastBody.vue')['default']
    TwoFADialog: typeof import('./src/components/TwoFADialog.vue')['default']
    UpdateDialog: typeof import('./src/components/UpdateDialog.vue')['default']
    Uptime: typeof import('./src/components/Uptime.vue')['default']
    VolumeList: typeof import('./src/components/VolumeList.vue')['default']
    VolumeListItem: typeof import('./src/components/VolumeListItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBModal: typeof import('bootstrap-vue-next')['vBModal']
  }
}
