services:
  website:
    image: ghcr.io/bewcloud/bewcloud:${BEWCLOUD_VERSION}
    restart: always
    ports:
      - "${BEWCLOUD_PORT}:8000"
    mem_limit: 256m
    env_file:
      - path: .env
        required: true
    volumes:
      - ./data-files:/app/data-files
    depends_on:
      - postgresql

  postgresql:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - bewcloud-db:/var/lib/postgresql/data
    mem_limit: 256m
    ulimits:
      memlock:
        soft: -1
        hard: -1

  radicale:
    image: tomsquest/docker-radicale:${RADICALE_VERSION}
    init: true
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    volumes:
      - radicale-data:/data
    mem_limit: 256m

volumes:
  bewcloud-db:
    driver: local
  radicale-data:
    driver: local
